// GET /api/jisho?q=<word> — dictionary lookup for the Add Vocab page.
//
// ("jisho" 辞書 just means "dictionary", so the route name still fits even
// though jisho.org is no longer the primary source. The path is unchanged so
// worker.js's ROUTES table and js/add-vocab.js keep working as-is.)
//
// WHY THIS IS NOT jisho.org ANY MORE — measured, not guessed (2026-08-16):
// jisho.org is unreachable from Cloudflare Workers. Every request from a real
// Worker (tested via `wrangler dev --remote`, so a genuine Cloudflare colo)
// comes back as HTTP 525 "SSL handshake failed", generated by Cloudflare
// itself, in ~165ms — the request never reaches jisho. Verified against
// https://jisho.org, https://www.jisho.org, plain http://, and with browser
// User-Agent/Accept headers: all 525. From an ordinary IP the same URL answers
// 200 in ~0.4s, and https://example.com answers 200 from the same Worker, so
// this is neither our egress nor jisho being down — jisho.org is blocking
// Cloudflare's shared Worker egress IPs at the TLS layer (a normal
// anti-scraping measure; their API is unofficial and they ask people not to
// hammer it). jisho.org is on ZoneEdit nameservers, so this is NOT the
// "fetching a Cloudflare zone from a Worker" trap — it is a deliberate block,
// and nothing we can set on fetch() gets around it.
//
// Jotoba (https://jotoba.de, open-source, JMdict-backed — the same dictionary
// data jisho.org uses) IS reachable: 5/5 test words returned 200 with real
// results in 35-64ms from the edge. So it is the primary source now, with
// jisho.org kept as a fallback purely as free insurance in case that block is
// ever lifted — it costs nothing on the happy path, since it is only tried
// after Jotoba has already failed.
//
// The response shape is UNCHANGED regardless of which source answered, so
// js/add-vocab.js needs no knowledge of any of this. Both mappers are
// allowlist projections — same discipline as _lib/kv.js#toPublic(): never
// forward third-party fields we haven't looked at.

import { json, err } from './_lib/http.js';
import { checkRateLimit } from './_lib/ratelimit.js';

const MAX_QUERY_LENGTH = 64;
const MAX_RESULTS = 12;
const MAX_SENSES = 5;
const LOOKUP_TIMEOUT_MS = 8000;

// js/add-vocab.js keys the "usually written in kana" checkbox off this exact
// string (it is jisho.org's wording). Jotoba encodes the same fact as the enum
// "UsuallyWrittenInKana", so translate it here rather than teaching the client
// about a second spelling.
const KANA_ALONE_TAG = 'Usually written using kana alone';
const JOTOBA_MISC_TAGS = { UsuallyWrittenInKana: KANA_ALONE_TAG };

export async function onRequestGet({ request, env, data }) {
  const q = new URL(request.url).searchParams.get('q')?.trim();
  if (!q) return err(400, 'bad_request', 'Enter a word to look up.');
  if (q.length > MAX_QUERY_LENGTH) {
    return err(400, 'bad_request', 'That search is too long.');
  }

  const { allowed, retryAfter } = await checkRateLimit(env, data.user.id, 'jisho');
  if (!allowed) {
    return err(429, 'rate_limited', `Too many lookups — try again in ${retryAfter}s.`);
  }

  // Each lookup reports { ok } separately from how many results it found.
  // Keeping those apart is the whole ballgame: "the source answered, and the
  // answer is that this word isn't in the dictionary" is a NORMAL result the
  // UI already handles ("No results — you can still add this word manually"),
  // while "the source is broken" is an outage. Collapsing the two makes every
  // unmatched word look like the service is down.
  const jotoba = await lookupJotoba(q);
  if (jotoba.ok && jotoba.results.length) {
    return json({ source: 'jotoba', results: jotoba.results });
  }

  const jisho = await lookupJisho(q);
  if (jisho.ok && jisho.results.length) {
    return json({ source: 'jisho', results: jisho.results });
  }

  // No matches anywhere. If at least one source actually answered, this is a
  // genuine "no such word", not a failure — 200 with an empty list.
  if (jotoba.ok || jisho.ok) {
    return json({ source: jotoba.ok ? 'jotoba' : 'jisho', results: [] });
  }

  return err(
    502,
    'lookup_failed',
    'The dictionary is not responding right now. You can still add the word manually.',
  );
}

/**
 * Jotoba's word search, with one retry. POST + JSON body, so Cloudflare's
 * `cf.cacheTtl*` options don't apply (they're GET/HEAD only) — acceptable,
 * since it answers in well under 100ms from the edge.
 *
 * The retry exists because this shares a Cloudflare egress IP with every other
 * Worker on the platform, so an occasional throttled or dropped response is
 * expected; at ~50ms a second attempt is far cheaper than making the user
 * retype their search.
 *
 * @returns {Promise<{ok: boolean, results: Array}>} `ok` says whether the
 *   source answered at all — which is NOT the same as whether it found
 *   anything. See the caller.
 */
async function lookupJotoba(q) {
  for (let attempt = 1; attempt <= 2; attempt++) {
    const outcome = await tryJotoba(q, attempt);
    if (outcome.ok) return outcome;
  }
  return { ok: false, results: [] };
}

async function tryJotoba(q, attempt) {
  let res;
  try {
    res = await fetch('https://jotoba.de/api/search/words', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
      body: JSON.stringify({ query: q, language: 'English', no_english: false }),
      signal: AbortSignal.timeout(LOOKUP_TIMEOUT_MS),
    });
  } catch (e) {
    console.error(`[jisho] jotoba fetch threw (attempt ${attempt})`, e);
    return { ok: false, results: [] };
  }

  if (!res.ok) {
    console.error(`[jisho] jotoba returned HTTP ${res.status} (attempt ${attempt})`);
    return { ok: false, results: [] };
  }

  let body;
  try {
    body = await res.json();
  } catch (e) {
    console.error(`[jisho] jotoba response was not valid JSON (attempt ${attempt})`, e);
    return { ok: false, results: [] };
  }

  const words = Array.isArray(body?.words) ? body.words : [];
  return { ok: true, results: words.slice(0, MAX_RESULTS).map(toJotobaEntry) };
}

function toJotobaEntry(word) {
  const kanji = typeof word?.reading?.kanji === 'string' ? word.reading.kanji : null;
  const kana = typeof word?.reading?.kana === 'string' ? word.reading.kana : '';

  return {
    slug: kanji || kana || null,
    isCommon: word?.common === true,
    // Jotoba exposes JLPT on kanji entries, not on word entries. The dropdown
    // renders this as an optional badge, so an empty list just omits it.
    jlpt: [],
    forms: [{ word: kanji, reading: kana }],
    senses: Array.isArray(word?.senses)
      ? word.senses.slice(0, MAX_SENSES).map((s) => ({
          english: Array.isArray(s?.glosses) ? s.glosses.filter((g) => typeof g === 'string') : [],
          partsOfSpeech: Array.isArray(s?.pos)
            ? s.pos.map(posLabel).filter((p) => typeof p === 'string')
            : [],
          tags: miscToTags(s?.misc),
        }))
      : [],
  };
}

/**
 * Jotoba's part-of-speech entries are either a bare string ("Noun") or a
 * single-key object that may nest one level: {"Verb":"Ichidan"} or
 * {"Verb":{"Godan":"RuIrreg"}}. Flattened to a readable label for display and
 * for custom_vocab.part_of_speech.
 */
function posLabel(pos) {
  if (typeof pos === 'string') return pos;
  if (!pos || typeof pos !== 'object') return null;

  const [key, value] = Object.entries(pos)[0] || [];
  if (!key) return null;
  if (typeof value === 'string') return `${key} (${value})`;
  if (value && typeof value === 'object') {
    const [inner, innerValue] = Object.entries(value)[0] || [];
    if (!inner) return key;
    return `${key} (${inner}${typeof innerValue === 'string' ? ` ${innerValue}` : ''})`;
  }
  return key;
}

/** Jotoba `misc` is a single enum string (or absent); jisho used a tag array. */
function miscToTags(misc) {
  const list = Array.isArray(misc) ? misc : misc ? [misc] : [];
  return list.filter((m) => typeof m === 'string').map((m) => JOTOBA_MISC_TAGS[m] || m);
}

/**
 * jisho.org's unofficial API — currently blocked from Cloudflare Workers (see
 * the file header), kept as a fallback in case that changes.
 *
 * @returns {Promise<{ok: boolean, results: Array}>} same contract as
 *   lookupJotoba: `ok` means "answered", not "found something".
 */
async function lookupJisho(q) {
  let res;
  try {
    res = await fetch(`https://jisho.org/api/v1/search/words?keyword=${encodeURIComponent(q)}`, {
      signal: AbortSignal.timeout(LOOKUP_TIMEOUT_MS),
      // Cache successes only. Plain `cacheTtl` + `cacheEverything` would cache
      // a transient 502 for the full 24h too, turning one hiccup into a day of
      // failures for that query at that colo.
      cf: { cacheTtlByStatus: { '200-299': 86400, '300-599': 0 } },
    });
  } catch (e) {
    console.error('[jisho] jisho.org fetch threw', e);
    return { ok: false, results: [] };
  }

  if (!res.ok) {
    console.error(`[jisho] jisho.org returned HTTP ${res.status}`);
    return { ok: false, results: [] };
  }

  let body;
  try {
    body = await res.json();
  } catch (e) {
    console.error('[jisho] jisho.org response was not valid JSON', e);
    return { ok: false, results: [] };
  }

  const entries = Array.isArray(body?.data) ? body.data : [];
  return { ok: true, results: entries.slice(0, MAX_RESULTS).map(toJishoEntry) };
}

function toJishoEntry(entry) {
  return {
    slug: typeof entry?.slug === 'string' ? entry.slug : null,
    isCommon: entry?.is_common === true,
    jlpt: Array.isArray(entry?.jlpt) ? entry.jlpt.filter((j) => typeof j === 'string') : [],
    forms: Array.isArray(entry?.japanese)
      ? entry.japanese.map((f) => ({
          word: typeof f?.word === 'string' ? f.word : null,
          reading: typeof f?.reading === 'string' ? f.reading : '',
        }))
      : [],
    senses: Array.isArray(entry?.senses)
      ? entry.senses.slice(0, MAX_SENSES).map((s) => ({
          english: Array.isArray(s?.english_definitions)
            ? s.english_definitions.filter((e) => typeof e === 'string')
            : [],
          partsOfSpeech: Array.isArray(s?.parts_of_speech)
            ? s.parts_of_speech.filter((p) => typeof p === 'string')
            : [],
          tags: Array.isArray(s?.tags) ? s.tags.filter((t) => typeof t === 'string') : [],
        }))
      : [],
  };
}
